---
# tasks file for apache
#
#

 - name: Installation de Apache et PHP
   yum:
     name: 
      - httpd
      - php
     state: present
 

 - name: Autorisations & permissions sur le repertoire
   file:
     path: /var/www/html
     state: directory
     mode: '0755'

 - name: Supression du fichier index.html
   file:
     path: /var/www/html/index.html
     state: absent

 - name: Clonage des fichiers php 
   copy:
     src: php/
     dest: /var/www/html/

 - name: restart and enable systemd apache service
   systemd:
    name: httpd
    enabled: yes
    state: restarted
