---
# tasks file for mariadb
#
- name: installation mysql
  yum:
   name: 
    - mariadb
    - mariadb-server
   state: present

- name: Activation et démarrage du serveur mariadb
  systemd:
   name: mariadb
   enabled: yes
   state: restarted

- name: setup mariadb
  command: "mysql -e \"UPDATE mysql.user SET Password = PASSWORD('Poseidon') WHERE User = 'root'\""

- name: Allow external MySQL connexions (1/2)
  lineinfile:
   path: /etc/my.cnf
   regexp: '^skip-external-locking'
   line: "# skip-external-locking"
      
- name: Allow external MySQL connexions (2/2)
  lineinfile:
   path: /etc/my.cnf
   regexp: '^bind-address'
   line: "# bind-address"

- name: Redémarrer le service SQL
  systemd:
   name: mariadb
   enabled: yes 
   state: restarted
