---
# tasks file for mariadb
#
- name: installation mysql
  yum:
   name: 
    - mariadb
    - mariadb-server
   state: present

- name: Activation et démarrage du serveur mariadb
  systemd:
   name: mariadb
   enabled: yes
   state: restarted

- name: Start mysql_secure_installation
  command: 'echo "& y y Mypasswd Mypasswd y y y y" | ./usr/bin/mysql_secure_installation'

- name: Redémarrer le service SQL
  systemd:
   name: mariadb
   enabled: yes 
   state: restarted
